name: "Delete GitHub Branches"

description: 'Deletes idle branches in GitHub repository'

author: tagdots

branding:
  icon: trash-2
  color: green

inputs:
  dry-run:
    description: 'Dry Run'
    default: 'true'
    required: false

  repo-url:
    description: 'Repository URL'
    default: ${{ github.server_url }}/${{ github.repository }}
    required: true

  exclude-branches:
    description: 'Branch(es) excluded from deletion'
    required: false

  max-idle-days:
    description: 'Maximum number of idle days (without new commits)'
    required: true

runs:
  using: "composite"

  steps:

  - name: Checkout source code
    uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

  - name: Install Python
    uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
    with:
      python-version: '3.14.x'

  - name: Install the latest delete-branches
    shell: bash
    run: python -m pip install -U delete-branches

  - name: Run delete-branches to show version
    shell: bash
    run: delete-branches --version

  - name: Run delete-branches
    shell: bash
    env:
      INPUT_DRY_RUN: "${{ inputs.dry-run }}"
      INPUT_REPO_URL: "${{ inputs.repo-url }}"
      INPUT_MAX_IDLE_DAYS: "${{ inputs.max-idle-days }}"
      INPUT_EXCLUDE_BRANCHES: "${{ inputs.exclude-branches }}"
    run: |
      # delete-branches
      if [[ -n "$INPUT_MAX_IDLE_DAYS" && "$INPUT_MAX_IDLE_DAYS" -ge 0 ]]; then
        COLUMNS=145 delete-branches \
          --dry-run "$INPUT_DRY_RUN" \
          --repo-url "$INPUT_REPO_URL" \
          --max-idle-days "$INPUT_MAX_IDLE_DAYS" \
          --exclude-branches "$INPUT_EXCLUDE_BRANCHES"
      else
        echo "Error: please check your inputs"
        exit 1
      fi
